version: "3.7"

services:
  server:
    image: golang:latest
    container_name: prom-server
    volumes:
      - ".:/promplayground"
    entrypoint: ["bash", "-c", "cd /promplayground; go get; go run /promplayground/cmd/server/*.go"]
    ports:
      - "8089:8089"

  prometheus:
    container_name: prom-prometheus
    image: prom/prometheus:latest
    volumes:
      - "./etc/prometheus:/etc/prometheus/"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
